apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devteam

resources:
  - namespace.yaml
  - mongo/deployment.yaml
  - meeting-board/deployment.yaml
  - personas/secrets.yaml
  - personas/deployments.yaml

commonLabels:
  app.kubernetes.io/part-of: devteam
